sonr-io/speedway

- server-in-memory/server.js
- server-in-memory/test.js
- src/pages/Buckets/ModalCreate.tsx
- src/pages/Objects/Container.tsx
- src/pages/Objects/components/NewObjectModalContent/Component.tsx
- src/pages/Objects/components/NewObjectModalContent/Container.tsx
- src/pages/Schemas/components/NewSchemaModalContent/Component.tsx
- src/pages/Signup/Container.tsx
- lint
- fix server.js
- object modal: improve css and fix console errors
- autofocus on bucket/schema modals
> Minor improvements

- .prettierignore
- server-in-memory/server.js
- server-in-memory/test-archetypes.js
- server-in-memory/test.js
- src/components/ErrorBoundary/index.tsx
- src/components/SearchableList/Component.tsx
- src/components/SearchableList/Container.tsx
- src/pages/Objects/Component.tsx
- src/pages/Objects/Container.tsx
- src/pages/Objects/components/NewObjectModalContent/Component.tsx
- src/pages/Objects/components/NewObjectModalContent/Container.tsx
- src/pages/Schemas/Component.tsx
- src/pages/Schemas/Container.tsx
- src/pages/Schemas/components/ViewProperties/Component.tsx
- src/pages/Schemas/components/ViewProperties/Container.tsx
- src/redux/slices/authenticationSlice.tsx
- src/redux/slices/objectsSlice.tsx
- src/redux/slices/schemasSlice.tsx
- src/service/account.ts
- src/service/buckets.ts
- src/service/objects.ts
- src/service/schemas.ts
- src/utils/checkLogin.ts
- src/utils/string.ts
- src/utils/types.ts
- normalize account layer
- normalize schema layer
> Normalize Fetch Layer 1/n

- src/pages/Objects/Container.tsx
- src/pages/Objects/components/NewObjectModalContent/Container.tsx
- src/pages/Schemas/Component.tsx
- src/pages/Schemas/components/ViewProperties/Container.tsx
- src/redux/slices/authenticationSlice.tsx
- src/redux/slices/bucketSlice.tsx
- src/redux/slices/objectsSlice.tsx
- src/redux/slices/schemasSlice.tsx
- src/service/addObjectToBucket.ts
- src/service/createAccount.ts
- src/service/createBucket.ts
- src/service/createObject.ts
- src/service/createSchema.ts
- src/service/getAccountInfo.ts
- src/service/getBuckets.ts
- src/service/getObjectsFromBucket.ts
- src/service/getSchemaFields.ts
- src/service/getSchemaMetadata.ts
- src/service/login.ts
- src/utils/checkLogin.ts
- src/utils/types.ts
made api layer params and return values less bureaucratic
> More api layer improvements

- go.mod
- go.sum
- Item 1
- Item 2
Fixes 
Connects 
> upgraded go.mod

- cmd/speedway-cli/speedwaycmd/bucket/bucket.go
- cmd/speedway-cli/speedwaycmd/bucket/create.go
- cmd/speedway-cli/speedwaycmd/bucket/get.go
- cmd/speedway-cli/speedwaycmd/object/builder.go
- cmd/speedway-cli/speedwaycmd/object/getobject.go
- cmd/speedway-cli/speedwaycmd/object/object.go
- cmd/speedway-cli/speedwaycmd/registry/Login.go
- cmd/speedway-cli/speedwaycmd/registry/Registry.go
- cmd/speedway-cli/speedwaycmd/registry/register.go
- cmd/speedway-cli/speedwaycmd/schema/create.go
- cmd/speedway-cli/speedwaycmd/schema/getschema.go
- cmd/speedway-cli/speedwaycmd/schema/schema.go
- go.sum
Refactor of the CLI command descriptions and usage. 
- ```speedway object get``` command changed to ```speedway object query```
N/A
N/A
Fixes #124 
Connects 
> initial change of usage and description

- src/pages/Objects/components/NewObjectModalContent/Container.tsx
- src/redux/slices/objectsSlice.tsx
- src/utils/promise.ts
- src/utils/types.ts
making multiple request not fail when there is at least one successful bucket is returned
Fixes 
Connects 
> feat: making multiple request safe

- .goreleaser.yaml
- go.sum
> Add homebrew support

- src/service/createSchema.ts
> fix: changing schema create response format

- server-in-memory/go.test.js
- server-in-memory/js.test.js
- server-in-memory/server.js
- src/service/createSchema.ts
> Update tests and serverjs according to schema changes

- cmd/speedway-cli/build.sh
- cmd/speedway-cli/speedwaycmd/schema/create.go
Modified field prompt label to reflect proper input
- create-schema (cli)
N/A
N/A
Fixes 
Connects 
> modified field prompt label

- src/assets/svgs/LeftSquaredIcon.tsx
- src/components/LayoutMenu/index.tsx
- src/components/SideMenu/Component.tsx
- src/components/SideMenu/Container.tsx
- src/components/SideMenu/components/ButtonsGroup.tsx
- src/components/SideMenu/components/MenuLink.tsx
- src/contexts/appSettingsContext/appSettingsContext.tsx
- src/contexts/appSettingsContext/appSettingsReducer.tsx
- src/index.tsx
- src/utils/constants.ts
creatting app settings context and making menu collapsible
Fixes 
Connects 
> feat: creatting app settings context and making menu collapsible

- server-in-memory/go.test.js
- server-in-memory/js.test.js
- server-in-memory/server.js
- server/routes/get-alias.go
- server/routes/proxy-query-alias.go
- server/routes/server.go
- add proxy endpoint so that we can discover wallet address from an alias
- add js endpoints for alias/buy and alias proxy
- tests for go and js
> Add endpoints related to aliases

- .github/workflows/release.yml
- cmd/speedway-cli/speedwaycmd/schema/create.go
- Item 1
- Item 2
Fixes 
Connects 
> changed runs-on OS

- server-in-memory/go.test.js
- server-in-memory/js.test.js
- server-in-memory/server.js
- server/routes/proxy-query-buckets.go
- server/routes/server.go
- src/service/getBuckets.ts
> Revert "Query buckets by creator"

- .prettierignore
> Add some files to .prettierignore

- server-in-memory/go.test.js
- server/routes/build-object.go
> Fix not being able to create objects with integer field

- src/pages/AliasCreation/Container.tsx
this change was lost somewhere
> Minor text update

- package-lock.json
- package.json
- server-in-memory/go.test.js
- server-in-memory/server.js
- src/pages/Buckets/Component.tsx
- src/service/getBuckets.ts
- src/utils/types.ts
- tailwind.config.js
- bucket list shows last update
- adding objects to bucket counts as an update
> Show last update on bucket list

- src/pages/Objects/Container.tsx
> Fix object list not loading on the first try after a login

- server-in-memory/server.js
> Fix bug on serverjs

- src/pages/Schemas/components/NewSchemaModalContent/Component.tsx
- src/pages/Schemas/components/NewSchemaModalContent/Container.tsx
- src/pages/Schemas/components/SchemaPropertyLine/Component.tsx
- src/pages/Schemas/components/SchemaPropertyLine/Container.tsx
- Add remove button to properties
> feat: delete property on schema creation

- src/pages/Objects/components/NewObjectModalContent/Component.tsx
> Update UI on object creation

- cmd/commands/bucket/create.go
- cmd/commands/bucket/query.go
- internal/client/bucket.go
- internal/daemon/bucket.go
-- migration of `bucket create` command to use the rpc client
- Item 1
- Item 2
Fixes 
Connects 
> migration of create bucket to use RPC client

- internal/client/schema.go
-- addition of rpc client call for GeSchemasbyCreator
- Item 1
- Item 2
Fixes 
Connects 
> update to rpc for schema by creator query

- server-in-memory/go.test.js
- server-in-memory/server.js
> Add file download support to serverjs
